### ISSUE TITLE
Essentials error on startup 

### ISSUE THREAD

**Issue by daneleo** [TorchAPI/Essentials#112]
Not sure if this will help, with the problems on the new update. This is the error I seam to get.

INFO] Essentials: Attempting to load config from C:\ProgramData\SpaceEngineersDedicated*****\Essentials.cfg
10:20:13.9287 [ERROR] Initializer: Error initializing server.
10:20:13.9287 [FATAL] Initializer: System.InvalidOperationException: Unable to generate a temporary class (result=1).
error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
at Torch.Persistent
1.Save(String path) in C:\jenkins\workspace\Torch_Torch_master\Torch\Persistent.cs:line 68
   at Torch.Persistent
1.Load(String path, Boolean saveIfNew) in C:\jenkins\workspace\Torch_Torch_master\Torch\Persistent.cs:line 92
at Essentials.EssentialsPlugin.Init(ITorchBase torch) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\EssentialsPlugin.cs:line 65
at Torch.Managers.PluginManager.LoadPlugins() in C:\jenkins\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 127
at Torch.TorchBase.Init() in C:\jenkins\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 338
at Torch.Server.TorchServer.Init() in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 100
at System.Threading.Tasks.Task.Execute()
System.InvalidOperationException: Unable to generate a temporary class (result=1).
error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
at Torch.Persistent
1.Save(String path) in C:\jenkins\workspace\Torch_Torch_master\Torch\Persistent.cs:line 68
   at Torch.Persistent
1.Load(String path, Boolean saveIfNew) in C:\jenkins\workspace\Torch_Torch_master\Torch\Persistent.cs:line 92
at Essentials.EssentialsPlugin.Init(ITorchBase torch) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\EssentialsPlugin.cs:line 65
at Torch.Managers.PluginManager.LoadPlugins() in C:\jenkins\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 127
at Torch.TorchBase.Init() in C:\jenkins\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 338
at Torch.Server.TorchServer.Init() in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 100
at System.Threading.Tasks.Task.Execute()

**Comment by rexxar-tc** [comment]
Fixed in latest version
