### ISSUE TITLE
Client crash on join with essentials plugin enabled

### ISSUE THREAD

**Issue by GeertCocu** [TorchAPI/Essentials#167]
Clean map, joining and seeing the spawning screen, about 5 seconds later the game crashes with the following exception:
```
2020-08-16 11:41:29.326 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at PRPIS.Hazards.PlayerHazardHud.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```
Space Engineers version: 1.196.013
Torch version: v1.3.1.127-master
Essentials version: v1.7.1.62-132-g2cd7b68

Other Plugins:
* Concealment (v1.4.1.21-21-g96540b3)
* ALE ShipFixer (v1.0.5.1)
* ALE Restart Watchdog (v1.0.2.1)
* DeathCounter (v1.0.1)
* HaE PBLimiter (v1.1.1.1)

**Comment by GeertCocu** [comment]
Upon further investigation this appears to be the culprit https://steamcommunity.com/sharedfiles/filedetails/?id=1846489995
