### ISSUE TITLE
Player is disconnected on join when Client Join Tweeks is enabled

### ISSUE THREAD

**Issue by leiflang** [TorchAPI/Essentials#174]
when a player joins they are kicked due to this error. If you disable Client Join tweaks (restart is not required) players can join.
``15:41:51.7771 [ERROR]  Keen: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_MISSION_TRIGGERS'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 125
   at Essentials.Patches.SessionDownloadPatch.PatchGetWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 276
   at Patched_Sandbox.Engine.Multiplayer.MyMultiplayerServerBaseOnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest(Int32 appVersion)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_MISSION_TRIGGERS'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 125
   at Essentials.Patches.SessionDownloadPatch.PatchGetWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 276
   at Patched_Sandbox.Engine.Multiplayer.MyMultiplayerServerBaseOnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest(Int32 appVersion)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)``

**Comment by DionisioVega82** [comment]
I am getting the same error message on my dedicated server for all users.

**Comment by N1Ran** [comment]
We took that shit out
