### ISSUE TITLE
Crash when using autocommands

### ISSUE THREAD

**Issue by iambenmitchell** [TorchAPI/Essentials#24]
I can create commands but when i go to edit them (GUI) the whole server crashes.

**Comment by Jimmacle** [comment]
This is resolved in the staging build.

**Comment by iambenmitchell** [comment]
Thanks for the fast reply! can you link me to the .dll :)

**Comment by Jimmacle** [comment]
This is currently only compatible with the staging build of Torch because of some changes to the plugin system.

https://build.torchapi.net/view/Torch%20Staging/job/Torch/job/Essentials/job/staging/lastSuccessfulBuild/artifact/bin/essentials.zip

**Comment by iambenmitchell** [comment]
22:40:14.0212 [ERROR] UpdateManager: An error occured downloading the plugin update for TorchAPI/Essentials.
22:40:14.0212 [ERROR] UpdateManager: System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Torch.Managers.UpdateManager.<CheckAndUpdatePlugin>d__9.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\UpdateManager.cs:line 86
22:40:14.0372 [INFO] PluginManager: Loading plugins
22:40:14.1622 [INFO] InstanceManager: Saved dedicated config.
22:40:14.9122 [INFO] InstanceManager: Saved world config.
22:40:14.9122 [INFO] Torch: Starting server.
2017-10-02 22:40:15.396: Bind IP : 0.0.0.0:27016
Setting breakpad minidump AppID = 244850
2017-10-02 22:40:18.632: Server successfully started
2017-10-02 22:40:18.632: Product name: Space Engineers
2017-10-02 22:40:18.633: Desc: Space Engineers
2017-10-02 22:40:18.633: Public IP: 88.99.101.74
2017-10-02 22:40:18.634: Steam ID: 90111334419023879
2017-10-02 22:40:19.872: Loading last session C:\Users\Administrator\Desktop\TakenSpace\Instance\Saves\TakenWorld
2017-10-02 22:40:20.148: Loading session: C:\Users\Administrator\Desktop\TakenSpace\Instance\Saves\TakenWorld
22:40:29.3291 [INFO] MultiplayerManager: Initializing Steam auth
22:40:29.3291 [INFO] MultiplayerManager: Steam auth initialized
22:40:29.3452 [INFO] Torch.Session.TorchSessionManager: Starting new torch session for TakenWorld
2017-10-02 22:40:29.349: Session loaded
2017-10-02 22:40:29.463: Server connected to Steam
2017-10-02 22:40:29.463: Server PolicyResponse (1)

**Comment by iambenmitchell** [comment]
Got that error when i replaced the essentials

**Comment by Jimmacle** [comment]
You should be able to ignore that one as long as the server continued loading.

**Comment by iambenmitchell** [comment]
Yep, But now the plugins tab is empty

**Comment by Jimmacle** [comment]
Hm, I'll look into it. If you don't need to edit the commands while the server is running you can edit Essentials.cfg manually before starting the server according to this format:

```
<EssentialsConfig>
  <AutoCommands>
    <AutoCommand>
      <Enabled>true</Enabled>
      <Command>!restart 900</Command>
      <DueTime>27900</DueTime>
      <Period>28800</Period>
    </AutoCommand>
  </AutoCommands>
</EssentialsConfig>

**Comment by iambenmitchell** [comment]
How do i repeat commands? Ie !save and !restart.
!say server restarting and updating in 1 min every 59mins
!save every 60mins
!restart every 61mins

**Comment by Jimmacle** [comment]
You'll want to set the `Period` to the repeat interval in seconds.

**Comment by Varaxian** [comment]
For instance, If you wanted to save every 15 minutes:

15 * 60 = 900 seconds

**Comment by Jimmacle** [comment]
Also, as an aside you can call `!restart [seconds]` to automatically count down to the restart.

**Comment by iambenmitchell** [comment]
ah thanks. But how do i have multiple commands?

**Comment by iambenmitchell** [comment]
Like whats the layout?

**Comment by Jimmacle** [comment]
Just repeat the AutoCommand block for each command you want.

**Comment by iambenmitchell** [comment]
Thanks

**Comment by iambenmitchell** [comment]
does !restart 20 Issue a save aswell?

**Comment by iambenmitchell** [comment]
I deleted my old config in the instance dir, As it was the only thing i could think of, however this did not fix my issue and the server didnt generate a new on. this leads me to believe that the plugin is not loading.

**Comment by iambenmitchell** [comment]
I didn't realise that you said i had to be on a staging build lol, I switched to it and it works fine.. for 10 secs then crashes. Bellow is the log.

18:06:59.3064 [INFO] SteamCMD: Checking for DS updates.
18:06:59.7317 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
18:06:59.8381 [INFO] SteamCMD: -- type 'quit' to exit --
18:06:59.9424 [INFO] SteamCMD: Loading Steam API...OK.
18:07:00.0473 [INFO] SteamCMD: 
18:07:00.7485 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
18:07:00.8530 [INFO] SteamCMD: Waiting for user info...OK
18:07:01.7243 [INFO] SteamCMD: Success! App '298740' already up to date.
18:07:02.8045 [INFO] SteamCMD: 
18:07:02.9099 [INFO] Initializer: Loading config C:\Users\Administrator\Desktop\TakenSpace\Torch.cfg
18:07:03.7963 [INFO] Torch: Init server 'Torch' at 'C:\Users\Administrator\Desktop\TakenSpace\Instance'
18:07:03.9547 [INFO] Torch: DEBUG
18:07:03.9547 [INFO] Torch: Torch Version: v1.2.0-43-g6f650c8
18:07:03.9547 [INFO] Torch: Game Version: 1.184.200
18:07:03.9547 [INFO] Torch: Executing assembly: Torch.Server, Version=1.2.0.11426, Culture=neutral, PublicKeyToken=null
18:07:03.9547 [INFO] Torch: Executing directory: C:\Users\Administrator\Desktop\TakenSpace\
18:07:03.9738 [INFO] PluginManager: Checking for plugin updates...
18:07:04.0239 [INFO] PluginManager: Updated 0 plugins.
18:07:04.0239 [INFO] PluginManager: Loading plugins...
18:07:04.0370 [INFO] PluginManager: Loading plugin 'Essentials' (v1.6.0-8-gf820b20)
18:07:04.0510 [INFO] PluginManager: Loaded 1 plugins.
18:07:04.4721 [ERROR] PluginManager: Unable to get the latest release of 'TorchAPI/Essentials.'
18:07:04.4721 [ERROR] PluginManager: Octokit.RateLimitExceededException: API rate limit exceeded for 88.99.101.74. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
   at Octokit.Connection.HandleErrors(IResponse response) in D:\repos\octokit.net\Octokit\Http\Connection.cs:line 612
   at Octokit.Connection.<RunRequest>d__55.MoveNext() in D:\repos\octokit.net\Octokit\Http\Connection.cs:line 589
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__54`1.MoveNext() in D:\repos\octokit.net\Octokit\Http\Connection.cs:line 573
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext() in D:\repos\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Torch.Managers.PluginManager.<GetLatestArchiveAsync>d__18.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Plugins\PluginManager.cs:line 185
{"message":"API rate limit exceeded for 88.99.101.74. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
18:07:04.4901 [ERROR] PluginManager: An error occurred updating the plugin Essentials.
18:07:04.4901 [ERROR] PluginManager: System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Managers.PluginManager.<>c__DisplayClass17_0.<<DownloadPluginUpdates>b__0>d.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Plugins\PluginManager.cs:line 154
18:07:06.7451 [INFO] InstanceManager: Saved dedicated config.
18:07:07.5293 [INFO] InstanceManager: Saved world config.
18:07:07.5342 [INFO] Torch: Starting server.
18:07:14.9607 [INFO] Torch.Session.TorchSessionManager: Starting new torch session for TakenWorld
18:07:21.5693 [ERROR] Torch.Session.TorchSessionManager: System.ArgumentException: Field 'ValidateAuthTicketResponse' defined on type 'VRage.Steam.MySteamGameServer' is not a field on the target object which is of type 'VRage.Steam.MySteamGameServer'.
   at System.Reflection.RtFieldInfo.CheckConsistency(Object target)
   at System.Reflection.RtFieldInfo.InternalGetValue(Object obj, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at Torch.Utils.ReflectedEventReplacer.<GetEventsInternal>d__17.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 342
   at Torch.Utils.ReflectedEventReplacer.Test(Object instance) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 276
   at Torch.Utils.ReflectedEventReplacer.Replace(Delegate newCallback, Object instance) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 296
   at Torch.Server.Managers.MultiplayerManagerDedicated.Attach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\MultiplayerManagerDedicated.cs:line 65
   at Torch.Managers.DependencyManager.Attach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\DependencyManager.cs:line 251
   at Torch.Session.TorchSession.Attach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSession.cs:line 41
   at Torch.Session.TorchSessionManager.SessionLoaded() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSessionManager.cs:line 99
18:07:24.9408 [INFO] Torch.Session.TorchSessionManager: Unloading torch session for TakenWorld
18:07:24.9408 [ERROR] Torch.Session.TorchSessionManager: System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.EventInfo.RemoveEventHandler(Object target, Delegate handler)
   at Torch.Utils.ReflectedEventReplacer.<>c__DisplayClass8_0.<.ctor>b__3(Delegate x) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 251
   at Torch.Utils.ReflectedEventReplacer.Restore(Object instance) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 318
   at Torch.Server.Managers.MultiplayerManagerDedicated.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\MultiplayerManagerDedicated.cs:line 74
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\DependencyManager.cs:line 263
   at Torch.Session.TorchSession.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSession.cs:line 46
   at Torch.Session.TorchSessionManager.SessionUnloaded() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSessionManager.cs:line 138
18:07:24.9608 [FATAL] Initializer: System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.EventInfo.RemoveEventHandler(Object target, Delegate handler)
   at Torch.Utils.ReflectedEventReplacer.<>c__DisplayClass8_0.<.ctor>b__3(Delegate x) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 251
   at Torch.Utils.ReflectedEventReplacer.Restore(Object instance) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 318
   at Torch.Server.Managers.MultiplayerManagerDedicated.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\MultiplayerManagerDedicated.cs:line 74
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\DependencyManager.cs:line 263
   at Torch.Session.TorchSession.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSession.cs:line 46
   at Torch.Session.TorchSessionManager.SessionUnloaded() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSessionManager.cs:line 144
   at System.Action.Invoke()
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.MySandboxGame.UnloadData_UpdateThread()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at Torch.Server.TorchServer.Start() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\TorchServer.cs:line 156
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by iambenmitchell** [comment]
Got it working finally, What is due time and period?

**Comment by Equinox-** [comment]
dueTime
The amount of time to delay before callback is invoked, in seconds.    Specify zero (0) to start the timer immediately.

period
The time interval between invocations of callback, in seconds.

**Comment by iambenmitchell** [comment]
okay thanks!

**Comment by iambenmitchell** [comment]
If i add the command do i then have to restart the server for it to load? or does saving the config apply changes?

**Comment by iambenmitchell** [comment]
As in do i need TO restart the server for the changes to take place?

**Comment by Jimmacle** [comment]
The autocommands update in real time, you don't need to restart the server.

**Comment by iambenmitchell** [comment]
thanks. when using sutocommands is the ! ran with the command? or should i be doing !restart

**Comment by Ketyi85** [comment]
hi help me !!!


 <?xml version="1.0" encoding="utf-8"?>
<EssentialsConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <AutoCommands>
    <AutoCommand>
      <Enabled>false</Enabled>
      <Command>!say Restart</Command>
      <DueTime>120</DueTime>
      <Period>122</Period>
    </AutoCommand>
    <AutoCommand>
      <Enabled>false</Enabled>
      <Command>restart</Command>
      <DueTime>150</DueTime>
      <Period>9900</Period>
    </AutoCommand>
  </AutoCommands>
</EssentialsConfig>

It does not write anything but crash

**Comment by DoubleRepo** [comment]
@Ketyi85  Do you mind stop posting your help questions in bug post threads ?
