### ISSUE TITLE
Improve command arg catch exception

### ISSUE THREAD

**Issue by szczepix** [TorchAPI/Essentials#8]
Essentials don't catch exception when command args is wrong.

```18:23:11.1764 [INFO] CommandManager: Server ran command '!cleanup scan'
18:24:05.1254 [INFO] CommandManager: Server ran command '!grids list'
18:30:22.3783 [INFO] CommandManager: Server ran command '!cleanup delete'
18:30:34.0603 [INFO] CommandManager: Server ran command '!cleanup delete no beacon'
18:31:30.2103 [INFO] CommandManager: Server ran command '!cleanup scan no beacon'
18:31:36.4033 [ERROR] Command: Command '/cleanup delete ' from 'Essentials' threw an exception. Args: nobeacon
18:31:36.4033 [ERROR] Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Essentials.Commands.CleanupModule.<ScanConditions>d__2.MoveNext()
   at Essentials.Commands.CleanupModule.Delete()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context)
18:31:36.4333 [INFO] CommandManager: Server ran command '!cleanup delete nobeacon'
18:31:43.7493 [INFO] CommandManager: Server ran command '!cleanup delete no beacon'
18:33:49.3403 [INFO] CommandManager: Server ran command '!cleanup scan notype beacon'
18:34:17.9913 [INFO] CommandManager: Server ran command '!cleanup delete notype beacon'
18:34:54.4963 [INFO] MultiplayerManager: szczepix (76561198019800973) Disconnected.
18:34:59.7493 [INFO] Torch: Stopping server.
18:34:59.7493 [INFO] Torch: Server stopped.
18:36:31.3983 [FATAL] Torch: System.Threading.ThreadStateException: Thread is not running; it cannot be suspended.
   at System.Threading.Thread.SuspendInternal()
   at System.Threading.Thread.Suspend()
   at Torch.Server.TorchServer.CheckServerResponding(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by Jimmacle** [comment]
It looks like it caught the exception properly. The fatal error is unrelated to Essentials, I'll add it to my bugfix list.
