### ISSUE TITLE
!faction clean does not clean empty factions

### ISSUE THREAD

**Issue by benjhook** [TorchAPI/Essentials#83]
The "!faction clean" command does not seem to function when trying to delete factions with less than 1 member. Usage example is "!faction clean 1", which results in a "cleaned 0 of 0 factions" response.

I frequently run "!identity purge 14" and this results in a lot of empty factions piling up. It'd be great to be able to clean those out via this command!

**Comment by rexxar-tc** [comment]
Should work on patron branch

**Comment by benjhook** [comment]
I've been using the patron branch. I'll come back with exact version number.

**Comment by benjhook** [comment]
Issue experienced using Essentials v1.7.1.11-37-g60cbfcc.

I know there is a newer version out however I'm unable to use it (reference https://github.com/TorchAPI/Essentials/issues/77) and I don't believe any updates to the "!faction clean" command were released since the version I'm running.

**Comment by benjhook** [comment]
Tested on latest version of Essentials (`Essentials v1.7.1.23-63-ga50a921`) and still an issue. 

Now throwing an exception, too.

```
14:19:24.0845 [ERROR]  Command: Command '!faction clean [Int32 memberCount] ' from 'Essentials' threw an exception. Args: 1
14:19:24.0845 [ERROR]  Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Essentials.Commands.WorldModule' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Essentials.Commands.WorldModule..cctor() in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 266
   --- End of inner exception stack trace ---
   at Essentials.Commands.WorldModule.RemoveFaction(MyFaction faction) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 240
   at Essentials.Commands.WorldModule.CleanFaction_Internal(Int32 memberCount) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 211
   at Essentials.Commands.WorldModule.CleanFactions(Int32 memberCount) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 96
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Essentials.Commands.WorldModule' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Essentials.Commands.WorldModule..cctor() in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 266
   --- End of inner exception stack trace ---
   at Essentials.Commands.WorldModule.RemoveFaction(MyFaction faction) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 240
   at Essentials.Commands.WorldModule.CleanFaction_Internal(Int32 memberCount) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 211
   at Essentials.Commands.WorldModule.CleanFactions(Int32 memberCount) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 96
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
```
