### ISSUE TITLE
!sandbox clean throws an exception

### ISSUE THREAD

**Issue by benjhook** [TorchAPI/Essentials#97]
Ever since the Survival Update the `!sandbox clean` command has been throwing this exception and doesn't seem to be working. Using `Essentials v1.7.1.23-63-ga50a921`.

```
14:11:06.2645 [ERROR]  Command: Command '!sandbox clean ' from 'Essentials' threw an exception. Args: 
14:11:06.2645 [ERROR]  Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Essentials.Commands.WorldModule' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Essentials.Commands.WorldModule..cctor() in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 266
   --- End of inner exception stack trace ---
   at Essentials.Commands.WorldModule.CleanSandbox() in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 324
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Essentials.Commands.WorldModule' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Essentials.Commands.WorldModule..cctor() in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 266
   --- End of inner exception stack trace ---
   at Essentials.Commands.WorldModule.CleanSandbox() in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 324
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
```

**Comment by N1Ran** [comment]
private static readonly FieldInfo GpsDicField = GpssField?.FieldType.GetField("m_playerGpss", BindingFlags.NonPublic | BindingFlags.Instance);

This is throwing a null reference.

**Comment by rexxar-tc** [comment]
Cannot reproduce. Please confirm the problem and re-open this issue if necessary.

**Comment by benjhook** [comment]
This was fixed in a previous patch. Close away!
