### ISSUE TITLE
!identity purge throws an exception

### ISSUE THREAD

**Issue by benjhook** [TorchAPI/Essentials#98]
Ever since the Survival Update the `!identity purge` command has been throwing this exception and doesn't seem to be working. Exact command entered is `!identity purge 14`. Using `Essentials v1.7.1.23-63-ga50a921`.

```
14:16:21.4274 [ERROR]  Command: Command '!identity purge <Int32 days> ' from 'Essentials' threw an exception. Args: 14
14:16:21.4274 [ERROR]  Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Essentials.Commands.WorldModule' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Essentials.Commands.WorldModule..cctor() in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 266
   --- End of inner exception stack trace ---
   at Essentials.Commands.WorldModule.RemoveFaction(MyFaction faction) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 240
   at Essentials.Commands.WorldModule.CleanFaction_Internal(Int32 memberCount) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 211
   at Essentials.Commands.WorldModule.PurgeIdentities(Int32 days) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 89
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Essentials.Commands.WorldModule' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Essentials.Commands.WorldModule..cctor() in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 266
   --- End of inner exception stack trace ---
   at Essentials.Commands.WorldModule.RemoveFaction(MyFaction faction) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 240
   at Essentials.Commands.WorldModule.CleanFaction_Internal(Int32 memberCount) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 211
   at Essentials.Commands.WorldModule.PurgeIdentities(Int32 days) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Commands\WorldModule.cs:line 89
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
```

**Comment by rexxar-tc** [comment]
Cannot reproduce.

**Comment by benjhook** [comment]
This was fixed in a previous patch. Close away!
